require "active_support"
require "active_model"
require_relative "active_record/base"
require_relative "active_record/schema"
require_relative "active_record/delegation"
require_relative "active_record/connection_adapters"
